baseurl             = "https://ugurhicyilmam.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "TR"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Uğur Hiçyılmam"
title               = "Bir yazılımcının notları..."
theme               = "cocoa"
pygmentsuseclasses  = true
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-62045338-3"
#
#[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"
#
[params]
author       = "Uğur Hiçyılmam"
locale       = "tr-TR"
cachebuster  = true # add the current unix timestamp in query string for cache busting css assets
dateform     = "02.01.2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = "Panik yapma"
email        = "ugurhicyilmam@gmail.com"
faviconfile  = "img/favicon.ico"
github       = "//github.com/ugurhicyilmam"
highlightjs  = true
linkedin     = "//linkedin.com/in/ugurhicyilmam"
twitter      = "//twitter.com/ugurhicyilmam"
selfIntro    = "developer, blogger" # appears in the site header when set to a non-empty string
paginate = 5
paginatePath  ="page"
#
#gravatar             = ""                # do not use in the same time as avatar
avatar                 = "img/profile.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
highlightjslanguages = ["go"]            # additional languages not included in the "common" set

#extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.

# The following are DEPRECATED.
#gatracker              = "XYZ" # use googleAnalytics instead
#initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.

